/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gold earrings glb.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gold earrings glb.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._gold_strings.geometry} material={materials['Material.002']} position={[0.631, 3.28, -0.709]} scale={[-0.03, -1.185, -0.03]} />
      <mesh geometry={nodes.screws.geometry} material={materials['Material.001']} position={[0.008, 4.88, -2.109]} rotation={[0, 0, -Math.PI / 2]} scale={[0.399, 0.164, 0.844]} />
      <mesh geometry={nodes.maincubes.geometry} material={materials.Material} position={[-0.019, 4.884, -0.697]} rotation={[0, Math.PI / 2, 0]} scale={[0.284, 0.51, 0.51]} />
    </group>
  )
}

useGLTF.preload('/gold earrings glb.glb')
