/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gold necklace glb.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gold necklace glb.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.black_jewels_.geometry} material={materials.BLACK} position={[32.538, 40.87, 0.375]} rotation={[1.571, 0, 0]} scale={0.966} />
      <mesh geometry={nodes.diamonds.geometry} material={materials.phong1} position={[32.538, 40.87, 0.375]} rotation={[1.571, 0, 0]} scale={0.966} />
      <mesh geometry={nodes.main_body_gold_.geometry} material={materials.gold} position={[39.248, 40.87, 0.375]} rotation={[1.571, 0, 0]} scale={0.966} />
      <mesh geometry={nodes.red_jewels.geometry} material={materials['red jewel']} position={[39.248, 40.87, 0.375]} rotation={[1.571, 0, 0]} scale={0.966} />
    </group>
  )
}

useGLTF.preload('/gold necklace glb.glb')
